### ISSUE TITLE
Security: authorized field in user metadata

### ISSUE THREAD

**Issue by ytvnr** [ytvnr/gif-of-the-day#101]
**Is your feature request related to a problem? Please describe.**
Add a registration step where admin have to validate user in database

**Describe the solution you'd like**
Add a "authorized" field on userMetadata for a user to be authorized to use the app.

**Comment by T3kstiil3** [comment]
He is difficult to restrict a filed to be edited by a user. Can we use organisation to defined if user is authorized ? Ex: if i am in a organisation (a organisation admin add me in her orga) i'm authorized !

**Comment by ytvnr** [comment]
we have to implement organization before opening the alpha, but why not, good idea

**Comment by ytvnr** [comment]
resolved by #110
