### ISSUE TITLE
Display tiles in home page

### ISSUE THREAD

**Issue by T3kstiil3** [ytvnr/gif-of-the-day#54]
- today team theme
- today gif
- ...

Something like giphy 
![image](https://user-images.githubusercontent.com/3717296/74334030-69e26080-4d99-11ea-965c-7e11d715d3e8.png)

https://www.reddit.com/r/vuetifyjs/comments/b880u8/masonry_grid/
https://www.npmjs.com/package/vue-masonry-css
https://github.com/PLDaily/vue2-waterfall

**Comment by T3kstiil3** [comment]
- le welcome
- le theme
- la team
- et des bloc de stats ...

**Comment by T3kstiil3** [comment]
https://vuetifyjs.com/fr-FR/components/cards/#horizontal-cards
https://vuetifyjs.com/fr-FR/components/cards/#twitter-card

**Comment by ytvnr** [comment]
will be resolved with #74
