### ISSUE TITLE
Rework home page

### ISSUE THREAD

**Issue by ytvnr** [ytvnr/gif-of-the-day#74]
**Describe the solution you'd like**
Use https://vuetifyjs.com/fr-FR/components/cards/#horizontal-cards for home page
- welcome
- team
- theme
- stats

**Comment by ytvnr** [comment]
see #54

**Comment by T3kstiil3** [comment]
https://github.com/ytvnr/gif-of-the-day/issues/54#issuecomment-601706726

**Comment by T3kstiil3** [comment]
@ytvnr to dont loose your awesome link : https://developers.giphy.com/docs/api/endpoint#translate

**Comment by T3kstiil3** [comment]
#77
