### ISSUE TITLE
[Documentation] Modelize database structure

### ISSUE THREAD

**Issue by ytvnr** [ytvnr/gif-of-the-day#75]
**Describe the solution you'd like**
https://highlyscalable.wordpress.com/2012/03/01/nosql-data-modeling-techniques/
https://mapr.com/blog/data-modeling-guidelines-nosql-json-document-databases/

**Additional context**
A contributor or a user that want to use the app on his own firebase should be able to know how the db is structured

**Comment by T3kstiil3** [comment]
Maybe can we have a look of CONTRIBUTING description of https://contribute-conference-hall.netlify.com/
And they use storybook 💙 for the documentation !
